name: build and push

on:
    release:
        types: [published]

jobs:
    docker:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  role-to-assume: ${{ secrets.ASSUME_ROLE }}
                  aws-region: us-east-1
                  mask-aws-account-id: yes

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag, and push image to Amazon ECR
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: techmove-bot
                  IMAGE_TAG: ${{ github.ref_name }}
                  STATIC_TAG: latest
              run: |
                  DOCKER_BUILDKIT=1 docker build -q -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$STATIC_TAG -f Dockerfile .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
